### ISSUE TITLE
Completion function never gets called

### ISSUE THREAD

**Issue by jayadamsmorgan** [ChimeHQ/LanguageServer#2]
When I trace the incoming ClientRequest from my client I get the following request:

```completion(LanguageServerProtocol.CompletionParams(textDocument: file:///home/ubuntu/Documents/PklLanguageServer/test.pkl, position: {0, 3}, context: Optional(LanguageServerProtocol.CompletionContext(triggerKind: LanguageServerProtocol.CompletionTriggerKind.triggerCharacter, triggerCharacter: Optional(".")))), (Function))```

However, the `completion()` function never gets called no matter what. Other functions like for example `semanticTokensFull` work fine. What can I do?

**Comment by mattmassicotte** [comment]
Thanks for opening this issue. Just for context - this repo was extracted from the work done on hylo language server. It was originally added to https://github.com/chimeHQ/LanguageServerProtocol.

I don't fully understand all of the internals yet, so this is something I still have to figure out.

**Comment by mattmassicotte** [comment]
Ok, so the `RequestHandler` type has a lot of default implementations and that's worrying me because those area easy to get wrong.

The type signature for completions is:

`func completion(id: JSONId, params: CompletionParams) async -> Response<CompletionResponse>`

but in your code it is:

`public func completion(id: JSONId, params: CompletionParams) async -> Result<CompletionList, AnyJSONRPCResponseError>`

Use of `Result` directly shouldn't be an issue but I don't think `CompletionResponse` is equivalent to `CompletionList`. Have to check.

**Comment by mattmassicotte** [comment]
No it is not. Try changing your signature to match the protocol exactly and see if fixes things.

**Comment by jayadamsmorgan** [comment]
Thank you so much, I didn't notice it, working fine now!

**Comment by mattmassicotte** [comment]
Fantastic!
